import * as React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import Stack from "@mui/material/Stack";
import { UserContext } from "@/context/userContext";
import Head from "next/head";
import NextBooking from "@/components/nextBooking";
import SaveCards from "@/components/saveCards";
import Image from "next/image";
import BannerPromo from "@/../public/bannerPromo.svg"
import MyCards from "@/components/myCards";
import Games from "@/components/games";

export default function Home() {
  const user = React.useContext(UserContext);
  return (
    <>
      <Head>
        <title>Neverland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <CssBaseline />
      <main>
        <Stack direction={"row"} justifyContent={"center"} marginTop={2}>
          <SaveCards />
        </Stack>
        <Stack direction={"row"} justifyContent={"center"} marginTop={2}>
          <MyCards />
        </Stack>
        <Stack direction={"row"} justifyContent={"center"} marginTop={2}>
          <NextBooking />
        </Stack>
        <Stack direction={"row"} justifyContent={"center"} marginTop={3}>
          <Image
            src={BannerPromo}
            alt="banner promo"
            component="div"
            sx={{
              width: "100%",
              height: "auto",
              margin: "auto",
            }}
          />
        </Stack>
        <Stack direction={"row"} justifyContent={"center"} marginTop={2}>
          <Games />
        </Stack>
      </main>
    </>
  );
}
