import * as React from "react";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import CssBaseline from "@mui/material/CssBaseline";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import { UserContext } from "@/context/userContext";
import Head from "next/head";
import Link from "next/link";
import NextBooking from "@/components/nextBooking";

export default function Home() {
  const cards = [1, 2, 3, 4, 5, 6];
  const imageUrls = [
    "/sucursal1.png",
    "/sucursal2.png",
    "/sucursal3.png",
    "/sucursal4.png",
    "/sucursal5.png",
    "/sucursal6.png",
  ];
  const user = React.useContext(UserContext);
  return (
    <>
      <Head>
        <title>Neverland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <main>
        <Box
          sx={{
            bgcolor: "background.paper",
            pt: 8,
            pb: 6,
          }}
        >
          <Stack
            direction="row"
            justifyContent="space-around"
            alignItems={"center"}
            flexWrap={"wrap"}
          >
            <Stack justifyContent={"flex-start"} alignItems={"flex-start"}>
              <Typography
                component="h3"
                variant="h5"
                align="center"
                color="text.primary"
                gutterBottom
              >
                ¡Hola, {user.user.name}!
              </Typography>
              <Typography
                variant="h5"
                align="center"
                color="text.secondary"
                paragraph
                textAlign={"left"}
              >
                Festejá tu cumpleaños en el lugar mas divertido
              </Typography>
            </Stack>
            <Link href="/mi-cumple" passHref>
              <Button
                variant="contained"
                sx={{
                  borderRadius: "20px",
                  backgroundColor: "#853AB6",
                  width: 170,
                  height: 100,
                }}
              >
                Reserva
              </Button>
            </Link>
          </Stack>
        </Box>
        <Stack direction={"roe"} justifyContent={"center"}>
          <NextBooking />
        </Stack>
        <Container sx={{ py: 8 }} maxWidth="md">
          <Typography
            variant="h4"
            align="left"
            color="text.primary"
            paragraph
            sx={{ py: 3 }}
          >
            Nuestras sucursales
          </Typography>
          <Grid container spacing={4}>
            {cards.map((card, index) => (
              <Grid item key={card} xs={12} sm={6} md={4}>
                <Card
                  sx={{
                    height: "100%",
                    display: "flex",
                    flexDirection: "column",
                  }}
                >
                  <CardMedia
                    component="div"
                    sx={{
                      pt: "56.25%",
                    }}
                    image={imageUrls[index % imageUrls.length]}
                    alt={`Image ${index}`}
                  />
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      </main>
    </>
  );
}
